apiVersion: v1
kind: Node
metadata:
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: 2018-01-10T16:15:18Z
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/hostname: 172.17.8.101
  name: 172.17.8.101
  resourceVersion: "230990"
  selfLink: /api/v1/nodes/172.17.8.101
  uid: 730c42ac-f621-11e7-989d-525400cae48b
spec:
  externalID: 172.17.8.101
status:
  addresses:
  - address: 172.17.8.101
    type: InternalIP
  - address: 172.17.8.101
    type: Hostname
  allocatable:
    cpu: "2"
    memory: 1781028Ki
    pods: "110"
  capacity:
    cpu: "2"
    memory: 1883428Ki
    pods: "110"
  conditions:
  - lastHeartbeatTime: 2018-01-13T15:33:20Z
    lastTransitionTime: 2018-01-10T16:15:16Z
    message: kubelet has sufficient disk space available
    reason: KubeletHasSufficientDisk
    status: "False"
    type: OutOfDisk
  - lastHeartbeatTime: 2018-01-13T15:33:20Z
    lastTransitionTime: 2018-01-12T16:07:43Z
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: 2018-01-13T15:33:20Z
    lastTransitionTime: 2018-01-12T16:07:43Z
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: 2018-01-13T15:33:20Z
    lastTransitionTime: 2018-01-12T16:14:53Z
    message: kubelet is posting ready status
    reason: KubeletReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  images:
  - names:
    - docker.io/openshift/origin-pod@sha256:f7988947caf542f560ee2421b61c8a077ad79263858189b3ed98a3fe7af88672
    - docker.io/openshift/origin-pod:latest
    sizeBytes: 228569038
  - names:
    - docker.io/centos@sha256:3b1a65e9a05f0a77b5e8a698d3359459904c2a354dc3b25ae2e2f5c95f0b3667
    - docker.io/centos:latest
    sizeBytes: 203538471
  - names:
    - docker.io/nginx@sha256:285b49d42c703fdf257d1e2422765c4ba9d3e37768d6ea83d7fe2043dad6e63d
    - docker.io/nginx:latest
    sizeBytes: 108472156
  - names:
    - docker.io/busybox@sha256:bbc3a03235220b170ba48a157dd097dd1379299370e1ed99ce976df0355d24f0
    - docker.io/busybox:latest
    sizeBytes: 1129289
  nodeInfo:
    architecture: amd64
    bootID: 5e9719e7-4000-44c8-a4e8-0a718c53b29b
    containerRuntimeVersion: docker://1.12.6
    kernelVersion: 3.10.0-693.5.2.el7.x86_64
    kubeProxyVersion: v1.9.0
    kubeletVersion: v1.9.0
    machineID: 0af5e342dc174d658888ca5cb1345efa
    operatingSystem: linux
    osImage: CentOS Linux 7 (Core)
    systemUUID: 0AF5E342-DC17-4D65-8888-CA5CB1345EFA
